<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SERVICE_BOOKING_MANAGEMENT_DAO\SERVICE_BOOKING_MANAGEMENT_DAO.csproj" />
  </ItemGroup>

</Project>
